stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive

# Build React client
build_client:
  stage: build
  image: node:18
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/build
    expire_in: 1 week
  only:
    - main

# Build PHP backend (lint + composer)
build_backend:
  stage: build
  image: php:8.2
  before_script:
    - apt-get update && apt-get install -y git unzip
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
  script:
    - cd backend
    - composer install --no-interaction --prefer-dist --no-progress
    - php -l api/register.php || true
    - php -l api/login.php || true
  artifacts:
    paths:
      - backend/vendor
    expire_in: 1 week
  only:
    - main

# Minify assets with Grunt
grunt_minify:
  stage: test
  image: node:18
  script:
    - cd grunt
    - npm ci
    - npx grunt
  dependencies:
    - build_client
  artifacts:
    paths:
      - client/build
    expire_in: 1 week
  only:
    - main

# Deploy to lab server via SSH (set CI variables: SSH_HOST, SSH_USER, SSH_PRIVATE_KEY)
deploy_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '' | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    # Send docker-compose + overlay files
    - rsync -avz docker-compose.yml $SSH_USER@$SSH_HOST:~/farmer-app/
    - rsync -avz backend $SSH_USER@$SSH_HOST:~/farmer-app/
    - rsync -avz client/Dockerfile $SSH_USER@$SSH_HOST:~/farmer-app/client/
    - ssh $SSH_USER@$SSH_HOST 'cd ~/farmer-app && docker compose up -d --build'
  environment:
    name: production
    url: https://YOUR-SUBDOMAIN-HERE/
  only:
    - main
